Update Redux store to display books 🤖
evansnyamekye/bookstore pull request #3
Opened 2023-09-27 08:45 UTC by evansnyamekye

### Update Redux store to display books 📖. 

This pull request updates the bookstore to use Redux in React components. Redux is a state management library that helps to keep the state of the application. 

**The following modifications/changes were applied:** 

- Added a store variable to the index.js file 📑. 
- Added connect and mapStateProps function to the Bookstore component ⏱️.
- Updated the home page component to use the store variable and the mapStateToProps function ⚛️.  

Thank you 😃.

2023-09-27 09:09 UTC, TedLivist requested changes
## STATUS: CHANGES REQUIRED ♻️ ♻️

Hi @evansnyamekye,

Good job so far!
✔️ Provider wrapper for app in `index.js` file
However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-27 09:09 UTC, TedLivist commented on src/components/AddBook.jsx
> +function AddBook() {
- [ ] Kindly look through your app. I cannot add a book. Regardless of what I submit, the book always defaults to Hunger Games. Kindly ensure the added books are reflected on the page.

2023-09-27 09:09 UTC, TedLivist commented on src/components/BookList.jsx
>        ))}
- [ ] I also cannot remove any book from the page, whether it is the initial book or the one added. The remove functionality does not at all. Kindly fix that.

2023-09-27 09:09 UTC, TedLivist commented on src/components/AddBook.jsx
> +    // const newId = uuidv4();
- [ ] Kindly remove commented code.

2023-09-27 09:09 UTC, TedLivist commented on src/components/BookList.jsx
> +/* eslint-disable import/no-extraneous-dependencies */
- [ ] Kindly avoid disabling linters as we need them to write clean code and maintain a standard

2023-09-27 09:09 UTC, TedLivist commented on src/redux/Store.js
>  /* eslint-disable import/no-extraneous-dependencies */
- [ ] Kindly remove linter disablings and fix the resulting linter error manually.

2023-09-27 09:09 UTC, TedLivist commented on src/redux/books/bookSlice.js
> +  ],
- [ ] These initial books are not listed on the page when I load the page. Kindly fix that.

  ![image](https://github.com/evansnyamekye/bookstore/assets/36542986/76113000-9867-41dd-839a-72675cbfdeba)

2023-09-28 18:16 UTC, Shedrack-Sunday approved these changes
Hi @evansnyamekye 

Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉

![image](https://github.com/krisbobo/blog-app/assets/50990925/76d09bb1-9dc7-46c0-be49-31f366afa4b8)


Highlights
- [x] Good project organization ✔️
- [x] Nice use of React features ✔️  
- [x] Kudus on meeting the requirements as  required  ✔️


Optional suggestions
Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-09-29 01:19 UTC, merged